### ISSUE TITLE
Not working on vim 7.4.541

### ISSUE THREAD

**Issue by AntoniosHadji** [tpope/vim-capslock#6]
When I first installed this plugin it worked as expected.  After upgrade to Vim 7.4.541 it no longer works.  I tried removing plugins that were installed after vim-capslock and it still does not work.  

when I execute `:imap` I see 
```
    i  <Plug>CapsLockDisable * <C-R>=<SNR>61_disable()<CR>
    i  <Plug>CapsLockEnable * <C-R>=<SNR>61_enable()<CR>
    i  <Plug>CapsLockToggle * <C-R>=<SNR>61_toggle()<CR>
    i  <C-G>c        <Plug>CapsLockToggle
```

What else can I do to debug my issue?

I'm running on Ubuntu 14.04.1 64 bit.

**Comment by AntoniosHadji** [comment]
I found the issue.  I had to increase `timeoutlen` to a greater value.  I had it set to only 50 based on a suggestion from `vim-airline` plugin.  The `<C-G>` was disappearing before I could hit the `c`

**Comment by tpope** [comment]
FYI, it's useful to shorten `ttimeoutlen`, not `timeoutlen`.

**Comment by AntoniosHadji** [comment]
Thanks!
