### ISSUE TITLE
Command-line capslock

### ISSUE THREAD

**Issue by mMontu** [tpope/vim-capslock#7]
I've just updated to the latest version and noticed that the cmap doesn't works anymore:

    cmap <C-L> <Plug>CapsLockToggle

Maybe I was abusing of an implementation detail, as the help file only mention insert mode. But I'm wondering if it is complicated to make it work on command line.

**Comment by mMontu** [comment]
I've just found the version I used before, 18f17, and `Gdiff` shows that `cnoremap <silent> <Plug>CapsLockToggle...` mappings were removed from plugin/capslock.vim, so it seems it was a design decision.

**Comment by tpope** [comment]
Broke it by accident and later removed it rather than bothering to fix. If you can figure out the problem I'd be happy to bring it back.

**Comment by mMontu** [comment]
Reading the code I noticed that the plugin is now based on InsertCharPre instead of remapping every key. There is no equivalent event for command-line mode, so I think the only way is to bring back the loop mapping and un-mapping the [A-Za-z] keys.

**Comment by tpope** [comment]
Yeah that's what I feared. I would be open to supporting both methods, as that would also allow supporting older versions of Vim.

**Comment by mMontu** [comment]
I think that would be somewhat simple to adjust my pull request to handle old Vim versions; maybe it could set a variable when initializing on older versions, and include a check for this var on the ` if a:mode == 'i'` lines and before defining autocmds.

**Comment by tpope** [comment]
Yeah, making it conditional on `exists('##InsertCharPre')` would be ideal.

**Comment by mMontu** [comment]
I've just updated the pull request.
