### ISSUE TITLE
How can I show the caplock status on vim airline

### ISSUE THREAD

**Issue by arthurkiller** [tpope/vim-capslock#9]
How can I show the caplock status on vim airline

> set statusline^=%{exists('*CapsLockStatusline')?CapsLockStatusline():''}
> let g:airline#extensions#capslock#enabled = 1
> set nocompatible

**Comment by arthurkiller** [comment]
it doesn't work correctly

**Comment by arthurkiller** [comment]
woo ,I see that , it only show the soft capslock status right?
Could it show the system capslock status?

**Comment by suxpert** [comment]
Perhaps you are looking for [vimcaps](https://github.com/suxpert/vimcaps)?

**Comment by arthurkiller** [comment]
resolved
